### ISSUE TITLE
Importing into 2020.1.6f1 causes pink material with no errors

### ISSUE THREAD

**Issue by cckelly** [flamacore/UnityHDRPSimpleWater#6]
Any idea what could be going on here? HDRP 8.2.0

**Comment by flamacore** [comment]
Well, 2020 is a whole different thing. Didn't try it on 2020 yet so can't comment but pink material means shader compilation error.  Could there be a problem or an inconsistency with your Shader Graph version rather than HDRP version? Or maybe if you open the shader in shader graph and try to see any errors in there?

As I said, not sure :)

**Comment by cckelly** [comment]
Ah so I checked this again, looks like it's throwing Assertion failed on expression: '0 == m_CurrentBufferBindMask[kUnityPerDraw]'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by cckelly** [comment]
Nevermind I found the issue, the unity package doesn't include the 3WaveGenerator so the Water shader graph can't find that sub graph.

**Comment by franz-xaver-hallhuber** [comment]
I cannot seem to find anything about this generator. Can you paste a link here?

**Comment by cckelly** [comment]
It’s not in the Unity package - it’s under the shaders directory. You need to download it from there.
